### ISSUE TITLE
Erronious error about tag not found

### ISSUE THREAD

**Issue by hellsworth** [ubuntu/desktop-snaps#112]
The gnome-dictionary workflow fails ([build log](https://github.com/ubuntu/gnome-dictionary/actions/runs/4998998217/jobs/8954952803)). The error is:

```
Part: gnome-dictionary
  Error: can't find the current tag in the tag list.
No updates available
```
But the [tag being used in the snap](https://github.com/ubuntu/gnome-dictionary/blob/stable/snapcraft.yaml#L35) is absolutely [a tag upstream](https://gitlab.gnome.org/Archive/gnome-dictionary/-/tree/40.0?ref_type=tags). So the error is wrong.

Also, if there *IS* an error, shouldn't the whole thing fail?

**Comment by sergio-costas** [comment]
The problem is that gnome-dictionary has been moved from GNOME to Archive, so what it's happening is that it can't find the project. I'll prepare a patch to detect this and send an specific message...

**Comment by sergio-costas** [comment]
Sent a patch that does a better check.

**Comment by hellsworth** [comment]
@sergio-costas In this case of gnome-dictionary, [the error messaging is better now](https://github.com/ubuntu/gnome-dictionary/actions/runs/5020176313/jobs/9001396299), but can we make the whole script throw a failure? If updatesnapyaml.py issues an error, then the workflow will fail and that's what I want if there is no valid URI.

**Comment by sergio-costas** [comment]
It makes sense...

**Comment by sergio-costas** [comment]
Done: https://github.com/ubuntu/desktop-snaps/pull/114
