### ISSUE TITLE
updatesnapyaml.py can't find snapcraft.yaml for gnome-text-editor

### ISSUE THREAD

**Issue by hellsworth** [ubuntu/desktop-snaps#115]
For gnome-text-editor, updatesnapyaml.py fails to find the snapcraft.yaml for some reason.

[gnome-text-editor workflow log](https://github.com/ubuntu/gnome-text-editor/actions/runs/5061496205/jobs/9085802926)

**Comment by sergio-costas** [comment]
Sent patch with fix.
