### ISSUE TITLE
updatesnapyaml.py reports no updates where there is a new update available

### ISSUE THREAD

**Issue by hellsworth** [ubuntu/desktop-snaps#116]
gnome-sudoku and gnome-system-monitor both say there are no updates available when there definitely are. gnome-sudoku is on tag 42.0 when there is a 44.0 upstream tag available. (and the exact same tag version and available upstream tag for gnome-system-monitor) 

[gnome-sudoku workflow log](https://github.com/ubuntu/gnome-sudoku/actions/runs/5061211791/jobs/9085115809)
[gnome-system-monitor workflow log](https://github.com/ubuntu/gnome-system-monitor/actions/runs/5061145639/jobs/9085008244)

When I run it locally, same thing:
```
heather@fenrir:~/Projects/snap-automation/desktop-snaps/updatesnap$ ./updatesnapyaml.py --github-user $GITHUB_USER --github-token $GITHUB_TOKEN https://github.com/ubuntu/gnome-sudoku.git
No updates available
```

**Comment by sergio-costas** [comment]
In gnome-sudoku, this is what is preventing it from updating to version 44:
![imagen](https://github.com/ubuntu/desktop-snaps/assets/105285003/c3ac11a7-1029-4f73-829f-2205cea38a31)

About gnome-system-monitor, I have to check it, because updatesnap.py does find the update, but updatesnapyaml.py doesn't... which is very odd because both are based in the same code.

**Comment by sergio-costas** [comment]
Odd... the 42.0 tag has a newer date than the 44.0 tag in gnome-system-monitor... That could be the problem...

![imagen](https://github.com/ubuntu/desktop-snaps/assets/105285003/50c7c045-f34e-4154-b67e-e807231f0ebd)

**Comment by sergio-costas** [comment]
Ok, no... they are nearly one year apart... O:-)

**Comment by sergio-costas** [comment]
Ok, I found the problem: the # ext:updatesnap comment is breaking the processing. I'll prepare a patch.

**Comment by sergio-costas** [comment]
fixed with https://github.com/ubuntu/desktop-snaps/pull/118

Also added https://github.com/ubuntu/desktop-snaps/pull/117
