### ISSUE TITLE
updatesnapyaml.py removing extra stuff, not just updating tag

### ISSUE THREAD

**Issue by hellsworth** [ubuntu/desktop-snaps#19]
When I run updatesnapyaml.py on gnome-calculator, it is [removing the meson plugin](https://github.com/ubuntu/gnome-calculator/pull/8/files) for some reason. I only expected the tag to be updated.

@sergio-costas could you please take a look at this?

**Comment by sergio-costas** [comment]
I'll check it right now. Also, clearly we have to add unitary tests. I'll begin with that too.

**Comment by sergio-costas** [comment]
I added a new pull request, #26 that should fix this and also add some unitary tests to avoid regressions. Can you test it when you have some spare time, please?
