### ISSUE TITLE
desktop snaps automation workflow taking GITHUB_USER as Ubuntu 

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/desktop-snaps#201]
After reading the blog, I installed the desktop snaps update automation workflow in this [repo](https://github.com/soumyaDghosh/audio-sharing-snap), but everytime I try, it's taking the `GITHUB_USER` as `ubuntu` making the workflow to fail. Is there anything that I'm doing wrong?

**Comment by hellsworth** [comment]
First, thanks for reading the blog and trying out my action and workflow!

No you're not doing anything wrong because the action was written for the ubuntu namespace, so [the `GITHUB_USER` is hardcoded as `ubuntu`](https://github.com/ubuntu/desktop-snaps/blob/stable/action.yml#L54). However, there's no reason this has to be so. I should be able to change this to import the `GITHUB_USER` (being sent as an input from the workflow to the action like [we do with the GITHUB_TOKEN](https://github.com/ubuntu/desktop-snaps/blob/stable/action.yml#L55)) and test it out before pushing.

**Comment by soumyaDghosh** [comment]
Thanks, it's gonna be very very useful for me, cause currently I maintain two content & sdk snaps and a lot of user snaps. Due to lack of interest/time, I am not getting anyone to maintain the personal snaps. So, this automation will help me a lot. As those repos are directly connected to launchpad and launchpad will build snap with each new change.

The links for you to the content and sdk snaps, if you would like to look into them once

1. https://github.com/soumyaDghosh/ffmpeg-sdk
2. https://github.com/soumyaDghosh/webkitgtk-sdk

**Comment by hellsworth** [comment]
Oh nice! ffmpeg and webkit are important sdk snaps indeed and I will make this usable for you :D

**Comment by hellsworth** [comment]
Ok I believe I have a solution that works. To test it though, could you please make [this same change to your workflow](https://github.com/ubuntu/gnome-calculator/commit/48842b4872476d3ebaedc51c674a504feac07e70)? That will test the action that is in a feature branch. I tested this with gnome-calculator and it works but I'd like to hear how it works for you before merging.

**Comment by soumyaDghosh** [comment]
Hii, the user is not hardcoded anymore, but the problem seems to be still there. 

```
remote: Permission to soumyaDghosh/audio-sharing-snap.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/soumyaDghosh/audio-sharing-snap.git/': The requested URL returned error: 403
Error: Invalid exit code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 128
}
Error: Invalid exit code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

Most likely this has something to do with the `GITHUB_TOKEN`. I have requested you as a collaborator. You can join there and do any change you may want to do. Sorry for this late reply.

**Comment by hellsworth** [comment]
Yep you're right, there's a permissions issue with using the GITHUB_TOKEN outside the ubuntu namespace it seems. To see this, compare [the GITHUB_TOKEN permissions of this repo, a repo outside ubuntu](https://github.com/soumyaDghosh/audio-sharing-snap/actions/runs/5472699846/jobs/9965201074#step:1:16) with [the GITHUB_TOKEN permissions of a repo inside ubuntu](https://github.com/ubuntu/gnome-calculator/actions/runs/5472672697/jobs/9965140246#step:1:16). The token needs write access. I know the desktop-snaps repo doesn't have any restrictive permissions on the token, so I suspect the ubuntu organization does have some permissions restrictions and I'm internally investigating who has admin access to the ubuntu organization to check the permissions there.

Again, thank you so much for bringing this to my attention so we can get it resolved :)

**Comment by soumyaDghosh** [comment]
> Yep you're right, there's a permissions issue with using the GITHUB_TOKEN outside the ubuntu namespace it seems. To see this, compare [the GITHUB_TOKEN permissions of this repo, a repo outside ubuntu](https://github.com/soumyaDghosh/audio-sharing-snap/actions/runs/5472699846/jobs/9965201074#step:1:16) with [the GITHUB_TOKEN permissions of a repo inside ubuntu](https://github.com/ubuntu/gnome-calculator/actions/runs/5472672697/jobs/9965140246#step:1:16). The token needs write access. I know the desktop-snaps repo doesn't have any restrictive permissions on the token, so I suspect the ubuntu organization does have some permissions restrictions and I'm internally investigating who has admin access to the ubuntu organization to check the permissions there.
> 
> Again, thank you so much for bringing this to my attention so we can get it resolved :)

I have looked into it, and what the changes needed is to give `GITHUB_TOKEN` permissions to `write-all`. Just adding this line will fix the issue. 
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

This is the commit that fixed it.

https://github.com/soumyaDghosh/audio-sharing-snap/commit/ecf3ee1e9d612dd0cad7b7735fb08c1abfbfbe7b

And this is now fixed for my repo also. Thanks for looking into this matter.

**Comment by hellsworth** [comment]
Thanks so much for this! I was working in parallel on my fork of your repo and you beat me to the solution. Great job!
