### ISSUE TITLE
updatesnapyaml.py: Tag not found when it exists

### ISSUE THREAD

**Issue by hellsworth** [ubuntu/desktop-snaps#223]
@sergio-costas 

We have uncovered a case with [the webkitgtk-sdk snap](https://github.com/soumyaDghosh/webkitgtk-sdk) where a part references an upstream tag that exists, but [updatesnapyaml.py can't find the tag](https://github.com/soumyaDghosh/webkitgtk-sdk/actions/runs/5487334691/jobs/9998653424#step:3:420) when processing the parts:

```
Part: webkitgtk-6-gnome-2204-sdk
  Error: can't find the current tag in the tag list.
```

The [upstream tag](https://github.com/WebKit/WebKit/tree/wpewebkit-2.40.1) definitely exists so what is going on?

This was first reported in #219 .

**Comment by soumyaDghosh** [comment]
Hii, another example is here. This is also same.

https://github.com/NickvisionApps/tagger-snap/actions/runs/5515909377/jobs/10056715442

**Comment by sergio-costas** [comment]
I'll check it right now.

**Comment by sergio-costas** [comment]
The problem is a subtle one: the tags for the updatesnap infor are write incorrectly: they need one extra space, to ensure that they are correctly aligned. Replace them with this:

```
# ext:updatesnap
#   version-format:
#     format: 'webkitgtk-%M.%m.%R'
```

**Comment by sergio-costas** [comment]
The other one... it works fine for me...

**Comment by soumyaDghosh** [comment]
> The other one... it works fine for me...

It didn't work with the beta tags

**Comment by soumyaDghosh** [comment]
> The problem is a subtle one: the tags for the updatesnap infor are write incorrectly: they need one extra space, to ensure that they are correctly aligned. Replace them with this:
> 
> ```
> # ext:updatesnap
> #   version-format:
> #     format: 'webkitgtk-%M.%m.%R'
> ```

sure, let me try

EDIT: Working.. :tada:
